[dependencies]
base = "0.9.7"
array = "https://github.com/aviate-labs/array.mo#v0.1.1"
encoding = "https://github.com/aviate-labs/encoding.mo#v0.3.1"
matchers = "https://github.com/kritzcreek/motoko-matchers#v1.2.0"
cap = "https://github.com/stephenandrews/cap-motoko-library#v1.0.4-alt"